### ISSUE TITLE
Import Project Error

### ISSUE THREAD

**Issue by alexntq** [pocmo/SensorDashboard#2]
Hi everyone,

Have anyone try to build this project on Anroid Studio 1.1.0, gradle 1.1.0, Windows 7 64bit?
I try to import this project on Android Studio 1.1.0 but I got the error message in Message Gradle Sync as following:

Gradle 'SensorDashboard-master' project refresh failed
Error:Unable to start the daemon process.
This problem might be caused by incorrect configuration of the daemon.
For example, an unrecognized jvm option is used.
Please refer to the user guide chapter on the daemon at http://gradle.org/docs/2.1/userguide/gradle_daemon.html
## Please read below process output to find out more:

java.lang.IllegalArgumentException: URI has an authority component
    at java.io.File.<init>(File.java:423)
    at org.gradle.api.internal.classpath.EffectiveClassPath.findAvailableClasspathFiles(EffectiveClassPath.java:41)
    at org.gradle.api.internal.classpath.EffectiveClassPath.<init>(EffectiveClassPath.java:32)
    at org.gradle.api.internal.classpath.DefaultModuleRegistry.<init>(DefaultModuleRegistry.java:61)
    at org.gradle.api.internal.classpath.DefaultModuleRegistry.<init>(DefaultModuleRegistry.java:55)
    at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:44)
    at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:35)
    at org.gradle.launcher.daemon.bootstrap.GradleDaemon.main(GradleDaemon.java:22)
- I try to modify the version number in build.gradle file but still not build successfully.

Thanks,

**Comment by thebino** [comment]
This isn't a problem with the project. You have to fix your local gradle installation. The gradle deamon couldn't be startet. Please reinstall gradle on your system and try it again. (You can also use the newest gradle 2.2.1)

**Comment by alexntq** [comment]
It works, Thebino. Thank for your support.
